# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-30 22:11
from __future__ import unicode_literals

import uuid
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edumanage', '0005_edb2_schema_part1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='instid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='serviceloc',
            name='locationid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='serviceloc',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='serviceloc',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude in decimal degrees, up to 8 decimal places', max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude in decimal degrees, up to 8 decimal places', max_digits=12)),
                ('altitude', models.DecimalField(decimal_places=3, help_text='Altitude, up to 9999 meters with millimeter precision', max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'Coordinates',
                'verbose_name_plural': 'Coordinates',
            },
        ),
        migrations.AddField(
            model_name='institutiondetails',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edumanage.Coordinates'),
        ),
        migrations.AddField(
            model_name='realm',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edumanage.Coordinates'),
        ),
        migrations.AddField(
            model_name='serviceloc',
            name='coordinates',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='edumanage.Coordinates'),
        ),
    ]
