# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edumanage', '0008_edb2_data_part2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutiondetails',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='institutiondetails',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='realm',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='realm',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='serviceloc',
            name='IPv6',
        ),
        migrations.RemoveField(
            model_name='serviceloc',
            name='NAT',
        ),
        migrations.RemoveField(
            model_name='serviceloc',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='serviceloc',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='serviceloc',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='serviceloc',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='serviceloc',
            name='port_restrict',
        ),
        migrations.RemoveField(
            model_name='serviceloc',
            name='transp_proxy',
        ),
    ]
