# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-23 22:23
from __future__ import unicode_literals

from django.db import migrations
import edumanage.models


class Migration(migrations.Migration):

    dependencies = [
        ('edumanage', '0009_edb2_schema_part3_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_i18n',
            name='city',
            field=edumanage.models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address_i18n',
            name='street',
            field=edumanage.models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=edumanage.models.CharField(db_column='contact_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='name_i18n',
            name='name',
            field=edumanage.models.CharField(max_length=255),
        ),
    ]
