# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-08 11:14
from __future__ import unicode_literals
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('edumanage', '0011_edb21_server_schema'),
    ]
    operations = [
        migrations.AddField(
            model_name='instserver',
            name='psk_identity',
            field=models.CharField(blank=True, help_text='Network Access Identifier (user@realm)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='instserver',
            name='psk_key',
            field=models.CharField(blank=True, help_text='Randomly-generated string', max_length=80, null=True),
        ),
    ]
