# Generated by Django 4.2.21 on 2025-05-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_registration', '0001_initial'),
        ('edumanage', '0013_instserver_psk'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "registration_registrationprofile"',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
