# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edumanage', '0011_edb21_server_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='ertype',
            field=models.PositiveIntegerField(choices=[(0, 'None (Stats Only)'), (1, 'IdP only'), (2, 'SP only'), (3, 'IdP and SP')], db_column='type'),
        ),
        migrations.AlterField(
            model_name='instserver',
            name='ertype',
            field=models.PositiveIntegerField(choices=[(0, 'None (Stats Only)'), (1, 'IdP only'), (2, 'SP only'), (3, 'IdP and SP')], db_column='type'),
        ),
    ]
