# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edumanage', '0100_stats_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='institutioncontactpool',
            options={'ordering': ['contact__name'], 'verbose_name': 'Instutution Contact (Pool)', 'verbose_name_plural': 'Instutution Contacts (Pool)'},
        ),
        migrations.AlterModelOptions(
            name='instrealm',
            options={'ordering': ['realm'], 'verbose_name': 'Institution Realm', 'verbose_name_plural': "Institutions' Realms"},
        ),
    ]
