# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edumanage', '0101_display_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monlocalauthnparam',
            name='eap_method',
            field=models.CharField(choices=[('PEAP', 'EAP-PEAP'), ('TTLS', 'EAP-TTLS'), ('TLS', 'EAP-TLS'), ('PWD', 'EAP-PWD')], max_length=16),
        ),
        migrations.AlterField(
            model_name='monlocalauthnparam',
            name='phase2',
            field=models.CharField(choices=[('PAP', 'PAP'), ('CHAP', 'CHAP'), ('MS-CHAPv2', 'MS-CHAPv2'), ('EAP-GTC', 'GTC')], max_length=16),
        ),
    ]
